export {default as Home} from './Home'
export {default as Shop} from './Shop'
export {default as View} from './View'
export {default as Cart} from './Cart'
export {default as Checkout} from './Checkout'