export const products = [
    {
        id: 1,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p1.webp',
    },
    {
        id: 2,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p2.webp',
    },
    {
        id: 3,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p3.webp',
    },
    {
        id: 4,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p4.webp',
    },
    {
        id: 5,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p5.webp',
    },
    {
        id: 6,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p6.webp',
    },
    {
        id: 7,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p7.webp',
    },
    {
        id: 8,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p8.webp',
    },
    {
        id: 1,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p1.webp',
    },
    {
        id: 2,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p2.webp',
    },
    {
        id: 3,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p3.webp',
    },
    {
        id: 4,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p4.webp',
    },
    {
        id: 5,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p5.webp',
    },
    {
        id: 6,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p6.webp',
    },
    {
        id: 7,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p7.webp',
    },
    {
        id: 8,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p8.webp',
    },
    {
        id: 1,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p1.webp',
    },
    {
        id: 2,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p2.webp',
    },
    {
        id: 3,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p3.webp',
    },
    {
        id: 4,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p4.webp',
    },
    {
        id: 5,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p5.webp',
    },
    {
        id: 6,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p6.webp',
    },
    {
        id: 7,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p7.webp',
    },
    {
        id: 8,
        name: 'addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: './img/product/p8.webp',
    },
];