export const products = [
    {
        id: 1,
        name: 'Addidas New Hammer sole for Sports person',
        price: 160,
        regularPrice: 220,
        imgUrl: '/img/product/p1.webp',
    },
    {
        id: 2,
        name: 'Addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: '/img/product/p2.webp',
    },
    {
        id: 3,
        name: 'Addidas New Hammer sole for Sports person',
        price: 165,
        regularPrice: 225,
        imgUrl: '/img/product/p3.webp',
    },
    {
        id: 4,
        name: 'Addidas New Hammer sole for Sports person',
        price: 180,
        regularPrice: 240,
        imgUrl: '/img/product/p4.webp',
    },
    {
        id: 5,
        name: 'Addidas New Hammer sole for Sports person',
        price: 170,
        regularPrice: 230,
        imgUrl: '/img/product/p5.webp',
    },
    {
        id: 6,
        name: 'Addidas New Hammer sole for Sports person',
        price: 185,
        regularPrice: 245,
        imgUrl: '/img/product/p6.webp',
    },
    {
        id: 7,
        name: 'Addidas New Hammer sole for Sports person',
        price: 175,
        regularPrice: 235,
        imgUrl: '/img/product/p7.webp',
    },
    {
        id: 8,
        name: 'Addidas New Hammer sole for Sports person',
        price: 190,
        regularPrice: 250,
        imgUrl: '/img/product/p8.webp',
    },
    {
        id: 1,
        name: 'Addidas New Hammer sole for Sports person',
        price: 160,
        regularPrice: 220,
        imgUrl: '/img/product/p1.webp',
    },
    {
        id: 2,
        name: 'Addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: '/img/product/p2.webp',
    },
    {
        id: 3,
        name: 'Addidas New Hammer sole for Sports person',
        price: 165,
        regularPrice: 225,
        imgUrl: '/img/product/p3.webp',
    },
    {
        id: 4,
        name: 'Addidas New Hammer sole for Sports person',
        price: 180,
        regularPrice: 240,
        imgUrl: '/img/product/p4.webp',
    },
    {
        id: 5,
        name: 'Addidas New Hammer sole for Sports person',
        price: 170,
        regularPrice: 230,
        imgUrl: '/img/product/p5.webp',
    },
    {
        id: 6,
        name: 'Addidas New Hammer sole for Sports person',
        price: 185,
        regularPrice: 245,
        imgUrl: '/img/product/p6.webp',
    },
    {
        id: 7,
        name: 'Addidas New Hammer sole for Sports person',
        price: 175,
        regularPrice: 235,
        imgUrl: '/img/product/p7.webp',
    },
    {
        id: 8,
        name: 'Addidas New Hammer sole for Sports person',
        price: 190,
        regularPrice: 250,
        imgUrl: '/img/product/p8.webp',
    },
    {
        id: 1,
        name: 'Addidas New Hammer sole for Sports person',
        price: 160,
        regularPrice: 220,
        imgUrl: '/img/product/p1.webp',
    },
    {
        id: 2,
        name: 'Addidas New Hammer sole for Sports person',
        price: 150,
        regularPrice: 210,
        imgUrl: '/img/product/p2.webp',
    },
    {
        id: 3,
        name: 'Addidas New Hammer sole for Sports person',
        price: 165,
        regularPrice: 225,
        imgUrl: '/img/product/p3.webp',
    },
    {
        id: 4,
        name: 'Addidas New Hammer sole for Sports person',
        price: 180,
        regularPrice: 240,
        imgUrl: '/img/product/p4.webp',
    },
    {
        id: 5,
        name: 'Addidas New Hammer sole for Sports person',
        price: 170,
        regularPrice: 230,
        imgUrl: '/img/product/p5.webp',
    },
    {
        id: 6,
        name: 'Addidas New Hammer sole for Sports person',
        price: 185,
        regularPrice: 245,
        imgUrl: '/img/product/p6.webp',
    },
    {
        id: 7,
        name: 'Addidas New Hammer sole for Sports person',
        price: 175,
        regularPrice: 235,
        imgUrl: '/img/product/p7.webp',
    },
    {
        id: 8,
        name: 'Addidas New Hammer sole for Sports person',
        price: 190,
        regularPrice: 250,
        imgUrl: '/img/product/p8.webp',
    },
];